# Generated by Django 5.0.3 on 2024-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confused', models.IntegerField()),
                ('lookingaway', models.IntegerField()),
                ('drowsy', models.IntegerField()),
                ('frustated', models.IntegerField()),
                ('engaged', models.IntegerField()),
                ('bored', models.IntegerField()),
            ],
        ),
    ]
